/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EasyAuction } from "./EasyAuction";
export type { ERC20 } from "./ERC20";

export { EasyAuction__factory } from "./factories/EasyAuction__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
